import { NextResponse } from "next/server";

/**
 * Relays an alert digest by email.
 *
 * The only server code in Ledgr, and deliberately the thinnest possible: it
 * takes a recipient and a list of alerts, sends one email, and stores nothing.
 * There is no account, no database row, and no log of the contents — the whole
 * point of the local-first design is that Ledgr's server never holds anyone's
 * financial data, and a "just for debugging" log would quietly undo that.
 */

export const runtime = "nodejs";

interface DigestAlert {
  severity: string;
  title: string;
  body: string;
}

const MAX_ALERTS = 50;
const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;

const SEVERITY_COLOR: Record<string, string> = {
  critical: "#d03b3b",
  serious: "#ec835a",
  warning: "#fab219",
  good: "#0ca30c",
};

const SEVERITY_LABEL: Record<string, string> = {
  critical: "Needs attention now",
  serious: "Important",
  warning: "Worth a look",
  good: "Heads up",
};

export async function POST(request: Request) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.RESEND_FROM;

  if (!apiKey || !from) {
    return NextResponse.json(
      {
        error:
          "Email delivery is not configured on this deployment. Set RESEND_API_KEY and RESEND_FROM to enable it.",
      },
      { status: 503 },
    );
  }

  let payload: { email?: unknown; alerts?: unknown };
  try {
    payload = await request.json();
  } catch {
    return NextResponse.json({ error: "Malformed request." }, { status: 400 });
  }

  const email = typeof payload.email === "string" ? payload.email.trim() : "";
  if (!EMAIL.test(email) || email.length > 254) {
    return NextResponse.json({ error: "That does not look like an email address." }, { status: 400 });
  }

  if (!Array.isArray(payload.alerts) || payload.alerts.length === 0) {
    return NextResponse.json({ error: "No alerts to send." }, { status: 400 });
  }

  const alerts: DigestAlert[] = payload.alerts.slice(0, MAX_ALERTS).map((raw) => {
    const item = raw as Record<string, unknown>;
    return {
      severity: typeof item.severity === "string" ? item.severity : "warning",
      title: String(item.title ?? "").slice(0, 200),
      body: String(item.body ?? "").slice(0, 600),
    };
  });

  try {
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from,
        to: [email],
        subject: subjectFor(alerts),
        html: renderDigest(alerts),
        text: renderPlain(alerts),
      }),
    });

    if (!response.ok) {
      // Deliberately not forwarding the provider's response body — it can echo
      // the recipient address and key metadata back to the browser.
      return NextResponse.json(
        { error: "The mail service rejected the message." },
        { status: 502 },
      );
    }

    return NextResponse.json({ ok: true });
  } catch {
    return NextResponse.json({ error: "Could not reach the mail service." }, { status: 502 });
  }
}

function subjectFor(alerts: DigestAlert[]): string {
  const critical = alerts.filter((a) => a.severity === "critical").length;
  if (critical > 0) {
    return `Ledgr: ${critical} thing${critical === 1 ? "" : "s"} needing attention`;
  }
  return `Ledgr: ${alerts.length} update${alerts.length === 1 ? "" : "s"} on your plan`;
}

/**
 * Escapes anything interpolated into the email HTML.
 *
 * Alert text is generated by Ledgr's own rules, but it embeds user-supplied
 * strings — merchant names and goal titles come from an imported spreadsheet
 * and a text field. Neither is trustworthy enough to drop into markup raw.
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function renderDigest(alerts: DigestAlert[]): string {
  const items = alerts
    .map(
      (alert) => `
        <tr>
          <td style="padding:0 0 20px 0;">
            <div style="border-left:3px solid ${SEVERITY_COLOR[alert.severity] ?? "#898781"};padding-left:14px;">
              <p style="margin:0 0 4px 0;font-size:12px;color:#52514e;">
                ${escapeHtml(SEVERITY_LABEL[alert.severity] ?? "Update")}
              </p>
              <p style="margin:0 0 6px 0;font-size:15px;font-weight:600;color:#0b0b0b;">
                ${escapeHtml(alert.title)}
              </p>
              <p style="margin:0;font-size:14px;line-height:1.55;color:#52514e;">
                ${escapeHtml(alert.body)}
              </p>
            </div>
          </td>
        </tr>`,
    )
    .join("");

  return `<!doctype html>
<html>
  <body style="margin:0;padding:24px;background:#f9f9f7;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;">
    <table role="presentation" cellpadding="0" cellspacing="0" style="max-width:560px;margin:0 auto;background:#fcfcfb;border-radius:12px;padding:28px;">
      <tr>
        <td style="padding-bottom:20px;">
          <p style="margin:0;font-size:18px;font-weight:600;color:#0b0b0b;">Your Ledgr digest</p>
          <p style="margin:6px 0 0 0;font-size:13px;color:#898781;">
            ${alerts.length} thing${alerts.length === 1 ? "" : "s"} Ledgr noticed. Open the app to act on any of them.
          </p>
        </td>
      </tr>
      ${items}
      <tr>
        <td style="padding-top:8px;border-top:1px solid #e1e0d9;">
          <p style="margin:16px 0 0 0;font-size:12px;line-height:1.6;color:#898781;">
            Sent because you turned on email digests in Ledgr. Your financial data stays in
            your browser — this email carries only the alert text above. Turn digests off in
            Settings at any time.
          </p>
        </td>
      </tr>
    </table>
  </body>
</html>`;
}

function renderPlain(alerts: DigestAlert[]): string {
  const lines = alerts.map(
    (alert) => `[${SEVERITY_LABEL[alert.severity] ?? "Update"}] ${alert.title}\n${alert.body}`,
  );

  return [
    "Your Ledgr digest",
    "",
    ...lines,
    "",
    "Sent because you turned on email digests in Ledgr. Your financial data stays in your browser — this email carries only the alert text above.",
  ].join("\n\n");
}
